// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameCourse = "course"

// Course mapped from table <course>
type Course struct {
	CID   string `gorm:"column:c_id;primaryKey" json:"c_id"`
	CName string `gorm:"column:c_name;not null" json:"c_name"`
	TID   string `gorm:"column:t_id;not null" json:"t_id"`
}

// TableName Course's table name
func (*Course) TableName() string {
	return TableNameCourse
}
