// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameScore = "score"

// Score mapped from table <score>
type Score struct {
	SID    string `gorm:"column:s_id;primaryKey" json:"s_id"`
	CID    string `gorm:"column:c_id;primaryKey" json:"c_id"`
	SScore int32  `gorm:"column:s_score" json:"s_score"`
}

// TableName Score's table name
func (*Score) TableName() string {
	return TableNameScore
}
