// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameStudent = "student"

// Student mapped from table <student>
type Student struct {
	SID    string `gorm:"column:s_id;primaryKey" json:"s_id"`
	SName  string `gorm:"column:s_name;not null" json:"s_name"`
	SBirth string `gorm:"column:s_birth;not null" json:"s_birth"`
	SSex   string `gorm:"column:s_sex;not null" json:"s_sex"`
}

// TableName Student's table name
func (*Student) TableName() string {
	return TableNameStudent
}
