// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameTeacher = "teacher"

// Teacher mapped from table <teacher>
type Teacher struct {
	TID   string `gorm:"column:t_id;primaryKey" json:"t_id"`
	TName string `gorm:"column:t_name;not null" json:"t_name"`
}

// TableName Teacher's table name
func (*Teacher) TableName() string {
	return TableNameTeacher
}
